ci: add unit test to github actions

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,17 +1,16 @@
 name: Java CI
 
-on: [push]
+on: [push, pull_request]
 
 env:
   SKIP_SIGNING: true
 
 jobs:
-  build:
-
+  acceptance:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
@@ -21,7 +20,6 @@ jobs:
       uses: gradle/actions/setup-gradle@v3
     - name: Setup Maven Action
       uses: s4u/setup-maven-action@v1.12.0
-    - run: docker ps
     - name: Download Embulk
       run: curl -o /tmp/embulk.jar -L https://dl.embulk.org/embulk-0.11.3.jar
     - name: Build with Gradle
@@ -44,3 +42,23 @@ jobs:
         ports:
           - 9042:9042
         options: --health-cmd "cqlsh --debug" --health-interval 10s --health-retries 10
+
+  test:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+    - name: Set up JDK
+      uses: actions/setup-java@v4
+      with:
+        distribution: temurin
+        java-version: '8'
+    - name: Setup Gradle
+      uses: gradle/actions/setup-gradle@v3
+    - name: Build with Gradle
+      run: ./gradlew test
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/test/TEST-*.xml'
